version: "3.8"

services:

  fuel_parser:
    build: .
    image: fuel_parser:1.0.1
    container_name: fuel_parser
    environment:
      BOT_TOKEN: ""
      DATABASE_PATH: /app/database/database.db
    command: ["python", "/app/main.py"]
    volumes:
      - type: bind
        source: ./database
        target: /app/database
